In [1]:
import numpy as np

In [18]:
A = np.array([[1,0,0],[5,1,0],[-2,3,1]])
B = np.array([[4,-2,1],[0,3,7],[0,0,2]])
A

array([[ 1,  0,  0],
       [ 5,  1,  0],
       [-2,  3,  1]])

In [19]:
B

array([[ 4, -2,  1],
       [ 0,  3,  7],
       [ 0,  0,  2]])

In [20]:
def multiplicacion(A,B):
    n = A.shape[0]
    m = B.shape[1]
    C = np.zeros((n,m))
    if n == m:
        for i in range(n):
            for j in range(m):
                fila = A[i,:]
                columna = B[:,j]
                term = 0
                for k in range(n):
                    term += fila[k]*columna[k]
                
                C[i,j] = term
        return C
    else:
        print("Las matrices ingresadas no son multiplicables")

In [21]:
multiplicacion(A,B)

array([[ 4., -2.,  1.],
       [20., -7., 12.],
       [-8., 13., 21.]])