In [1]:
import numpy as np

In [2]:
e1 = lambda x,y,z : 3*x -y -z #1
e2 = lambda x,y,z : -x+3*y+z #3
e3 = lambda x,y,z : 2*x+y+4*z #7

In [3]:
A = np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
b = np.array([[1],[3],[7]])
A

array([[ 3, -1, -1],
       [-1,  3,  1],
       [ 2,  1,  4]])

In [4]:
b

array([[1],
       [3],
       [7]])

In [5]:
def sor(A,B,w,X,lim=1000):
    """
    w debe estar entre 1 y 2 (excluyente)
    """
    n,m = A.shape

    k=0
    encontrado = False
    
    while k < lim and encontrado == False:
        X_k = np.zeros_like(X)
        
        for i in range(m):
            sum1 = 0
            sum2 = 0
            
            if 0 < i:
                for j in range(i-1):
                    sum1 += A[i,j]*X_k[j,0]
                    
            if i < n: 
                for j in range(i+1,n):
                    sum2 += A[i,j]*X[j,0]                                
                
            X_k[i] = (1-w)*X[i] + (w/A[i,i])*(B[i,0] - sum1-sum2)
            
            X = X_k 
            
        if (X[0]==1 and X[1]==1 and X[2]==1):
            encontrado = True
            
        else:
            k += 1
            
    return X,k
            
            

In [6]:
X_i = np.array([[0],[0],[0]]) 
W = np.linspace(1.01,1.99,17)
IT = np.zeros_like(W)
X=[]
for i in range(W.size):
    w = W[i]
    _,IT[i] = sor(A,b,w,X_i)
    X.append(sor(A,b,w,X_i))
    
IT

C:\Users\USER\AppData\Local\Temp\ipykernel_11316\52674995.py:19: RuntimeWarning: overflow encountered in long_scalars
  sum1 += A[i,j]*X_k[j,0]


array([   1.,    1.,    1.,    1.,    1.,    1.,    1.,    1., 1000.,
       1000., 1000., 1000., 1000., 1000., 1000., 1000., 1000.])

In [7]:
W

array([1.01   , 1.07125, 1.1325 , 1.19375, 1.255  , 1.31625, 1.3775 ,
       1.43875, 1.5    , 1.56125, 1.6225 , 1.68375, 1.745  , 1.80625,
       1.8675 , 1.92875, 1.99   ])

In [8]:
X

[(array([[1],
         [1],
         [1]]),
  1),
 (array([[1],
         [1],
         [1]]),
  1),
 (array([[1],
         [1],
         [1]]),
  1),
 (array([[1],
         [1],
         [1]]),
  1),
 (array([[1],
         [1],
         [1]]),
  1),
 (array([[1],
         [1],
         [1]]),
  1),
 (array([[1],
         [1],
         [1]]),
  1),
 (array([[1],
         [1],
         [1]]),
  1),
 (array([[2],
         [1],
         [1]]),
  1000),
 (array([[2],
         [1],
         [1]]),
  1000),
 (array([[2],
         [1],
         [1]]),
  1000),
 (array([[2],
         [1],
         [1]]),
  1000),
 (array([[2],
         [1],
         [1]]),
  1000),
 (array([[ 554297885],
         [         1],
         [-500600274]]),
  1000),
 (array([[1319716479],
         [         1],
         [ 772927597]]),
  1000),
 (array([[ 974732730],
         [         1],
         [-940007873]]),
  1000),
 (array([[ 556447213],
         [         1],
         [-553664973]]),
  1000)]

Para encontrar el valor de $\omega$ que minimiza el número de iteraciones, probé el método SOR con 17 valores diferentes de $\omega$ entre 1.01 y 1.99. Pude notar que la función convergió en una sola iteración para los valores que estaban entre 1.01 y 1.5. Adicionalmente verifiqué que, en efecto, los valores de $\vec{x}$ para esos valores de $\omega$ eran $(1,1,1)$. Así que procedí a probar el método con $\omega = 1.001, \omega = 1.0001, \omega = 1.00001, ...$ y $\omega = 1.499, \omega = 1.4999, \omega = 1.49999, ...$ 

In [9]:
sor(A,b,1.00001,X_i)

(array([[1],
        [1],
        [1]]),
 1)

In [10]:
sor(A,b,1.49999,X_i)

(array([[1],
        [1],
        [1]]),
 1)

De esta forma, confirmé que para valores donde $\omega \rightarrow 1$ y donde $\omega \rightarrow 1.5$, la función también converge con 1 iteración. Con base en lo anterior, concluí que los valores de $\omega$ que minimizan el número de iteraciones son los que cumplen que $\omega \in (1,1.5)$.